name: ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_slider: ^1.1.0

  input_quantity: ^1.1.6
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  razorpay_flutter: ^1.3.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
